idf_component_register(
    SRCS
        "ui.c"
        "ui_task.c"
        "ui_state_machine.c"
        "ui_render.c"
        "ui_status.c"
        "ui_text.c"
        "pages/page_base.c"
        "pages/page_main.c"
        "pages/page_list.c"
        "pages/page_message.c"
        "pages/page_settings.c"
    INCLUDE_DIRS
        "include"
        "."
        "pages"
    REQUIRES
        board storage
    PRIV_REQUIRES
        ble
        u8g2
        freertos
        esp_timer
)
