#pragma once
#include "driver/gpio.h"
#include "sdkconfig.h"

#define BOARD_I2C_SDA_IO GPIO_NUM_21
#define BOARD_I2C_SCL_IO GPIO_NUM_20
#define BOARD_GPIO_KEY_UP GPIO_NUM_5
#define BOARD_GPIO_KEY_DOWN GPIO_NUM_6
#define BOARD_GPIO_KEY_ENTER GPIO_NUM_7
#define BOARD_GPIO_KEY_BACK GPIO_NUM_8
#define BOARD_GPIO_VIBRATE GPIO_NUM_10
#define BOARD_GPIO_BATTERY GPIO_NUM_4
#define BOARD_GPIO_LED_1 GPIO_NUM_0
#define BOARD_GPIO_LED_2 GPIO_NUM_1
#define BOARD_GPIO_LED_3 GPIO_NUM_3
#define BOARD_GPIO_DISPLAY_RESET GPIO_NUM_2

// 其他通用常量
#define BOARD_I2C_FREQ_HZ 400000
#define BOARD_OLED_I2C_ADDRESS 0x3C

// ESP32C3 是单核芯片，应用任务运行在 Core 0
#define BOARD_APP_CPU 0

#define BOARD_TAG "board"